data.img_h: 384 
data.img_w: 640 
data.name: nocs_llff
data.img_pre_downsample_ratio: 1.0
data.per_gpu_batch_size: 1
data.training_set_path: nocs
data.visible_point_count: 256
lr.backbone_lr: 0.001
lr.decay_gamma: 0.1
lr.decay_steps: 60,90,120
lr.decoder_lr: 0.001
lr.weight_decay: 4.0e-05
loss.smoothness_lambda_v1: 0.0
loss.smoothness_gmin: 0.8
loss.smoothness_grad_ratio: 0.2
loss.smoothness_lambda_v2: 0.0
training.epochs: 2000
training.eval_interval: 500
